[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
bridge_solana = "HEMyDNhTcEu1Xhqk4pUMTQvQ42kx3C63FBjN4BgBTXnB"

[programs.localnet]
bridge_solana = "HEMyDNhTcEu1Xhqk4pUMTQvQ42kx3C63FBjN4BgBTXnB"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/home/solashi/.config/solana/id.json"

[scripts]
initialize = "yarn run ts-node -r tsconfig-paths/register scripts/initialize.ts"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
