[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
bridge_solana = "3s5RTyytWRct96npYMiBvpQ9CbbjecgFaibvsSS4vPWn"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/solashi/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
