[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
bridge_solana = "7EocgqrRm3AzYotTpATdwh7Uwyc1Zcn2mQELAw7b6HE6"

[programs.localnet]
bridge_solana = "7EocgqrRm3AzYotTpATdwh7Uwyc1Zcn2mQELAw7b6HE6"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/home/solashi/.config/solana/id.json"

[scripts]
create-bridge = "yarn run ts-node -r tsconfig-paths/register scripts/create-bridge.ts"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
